version: '3.12'

services:
  gen_service_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      API_KEY: sk-xxx-your-api-key
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  arq_worker_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      API_KEY: sk-xxx-your-api-key
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    command: ["arq", "src.genservice.arq_worker.WorkerSettings"]

  redis:
    image: redis:7
    ports:
      - "6379:6379"


